name: Run cypress tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - feature/*
      - e2e-tests/*

defaults:
  run:
    shell: bash

jobs:
  build:
    timeout-minutes: 25

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: cd frontend && npm install

      - name: Start backend and Run e2e tests
        run: |
          export LANG="de_DE.UTF-8"
          export TZ="Europe/Berlin"
          mvn -B package -PlocalDev -DskipTests -f backend/pom.xml &&
          java -Dspring.profiles.active=develop -jar backend/target/*.jar &
          sleep 60
          cd frontend && npm run e2e  -- --cypressConfig apps/quarano-frontend-e2e/cypress-ci.json --browser firefox
          kill -2 `lsof -i:8080 -t`

      - uses: actions/upload-artifact@v2
        name: Upload videos
        if: always()
        with:
          name: cypress-videos
          path: frontend/dist/cypress/apps/quarano-frontend-e2e/videos
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v2
        name: Upload screenshots
        if: always()
        with:
          name: cypress-screenshots
          path: frontend/dist/cypress/apps/quarano-frontend-e2e/screenshots
          if-no-files-found: ignore
